[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev"

[deploy]
startCommand = "chmod -R 777 storage bootstrap/cache && php artisan migrate --force && php -S 0.0.0.0:8080 -t public"
healthcheckPath = "/"
healthcheckTimeout = 100 